# Generated by Django 5.2.7 on 2026-04-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=35, unique=True)),
                ('e2eid', models.CharField(blank=True, default='', max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('qr_code_payload', models.TextField()),
                ('qr_code_image_b64', models.TextField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('expiracao_segundos', models.IntegerField(default=3600)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.order')),
            ],
            options={
                'verbose_name': 'Pagamento PIX',
                'verbose_name_plural': 'Pagamentos PIX',
                'ordering': ['-criado_em'],
            },
        ),
    ]
