# Generated by Django 5.2.7 on 2026-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentopix',
            name='e2eid',
        ),
        migrations.AddField(
            model_name='pagamentopix',
            name='asaas_customer_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamentopix',
            name='txid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
