# Generated by Django 5.2.7 on 2026-04-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_asaas_fields'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagamento_externo', models.CharField(db_column='IdPagamentoExterno', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_process', 'Em processamento'), ('in_mediation', 'Em mediação'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], db_column='Status', default='pending', max_length=30)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de crédito')], db_column='MetodoPagamento', max_length=20)),
                ('valor_total', models.DecimalField(db_column='ValorTotal', decimal_places=2, max_digits=10)),
                ('qr_code_payload', models.TextField(blank=True, default='')),
                ('qr_code_image_b64', models.TextField(blank=True, default='')),
                ('ticket_url', models.URLField(blank=True, default='', max_length=512)),
                ('expiracao_segundos', models.IntegerField(default=3600)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('status_detalhe', models.CharField(blank=True, default='', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='DataCriacao')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_column='DataAtualizacao')),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='PagamentoPix',
        ),
    ]
