# Generated by Django 5.2.7 on 2026-04-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='altura',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=6, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='comprimento',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=6, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='largura',
            field=models.DecimalField(decimal_places=1, default=15.0, max_digits=6, verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=6, verbose_name='Peso (kg)'),
        ),
    ]
