# Generated by Django 5.2.7 on 2026-04-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frete_prazo_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prazo (dias)'),
        ),
        migrations.AddField(
            model_name='order',
            name='frete_servico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serviço de Frete'),
        ),
        migrations.AddField(
            model_name='order',
            name='frete_transportadora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='frete_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do Frete'),
        ),
    ]
