# Generated by Django 5.2.7 on 2026-04-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_order_frete_prazo_dias_order_frete_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
    ]
